/* This file was generated by SableCC (http://www.sablecc.org/). 
 * Then modified.
 */

package ast.node;

import ast.visitor.*;

@SuppressWarnings("nls")
public final class IdLiteral extends ILiteral
{
    public IdLiteral(int _line_, int _pos_, String _id_)
    {
        super(_line_, _pos_,_id_,0);
    }

    @Override
    public int getNumExpChildren() { return 0; }
    
    @Override
    public Object clone()
    {
        return new IdLiteral(
                this.getLine(),
                this.getPos(),
                this.getLexeme());
    }

    public void accept(Visitor v)
    {
        v.visitIdLiteral(this);
    }

    @Override
    void removeChild(Node child)
    {
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(Node oldChild, Node newChild)
    {
        throw new RuntimeException("Not a child.");
    }
}
