/* This file was generated by SableCC (http://www.sablecc.org/). 
 * Then modified.
 */

package ast.node;

import ast.visitor.*;

@SuppressWarnings("nls")
public final class WhileStatement extends IStatement
{
    private IExp _exp_;
    private IStatement _statement_;

    public WhileStatement(int _line_, int _pos_, 
            IExp _exp_, IStatement _statement_)
    {
        super(_line_, _pos_);
        
        setExp(_exp_);

        setStatement(_statement_);

    }

    @Override
    public int getNumExpChildren() { return 1; }
    
    @Override
    public Object clone()
    {
        return new WhileStatement(
                this.getLine(),
                this.getPos(),
                cloneNode(this._exp_),
                cloneNode(this._statement_));
    }

    public void accept(Visitor v)
    {
        v.visitWhileStatement(this);
    }

    public IExp getExp()
    {
        return this._exp_;
    }

    public void setExp(IExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public IStatement getStatement()
    {
        return this._statement_;
    }

    public void setStatement(IStatement node)
    {
        if(this._statement_ != null)
        {
            this._statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statement_ = node;
    }

    @Override
    void removeChild(Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._statement_ == child)
        {
            this._statement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(Node oldChild, Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((IExp) newChild);
            return;
        }

        if(this._statement_ == oldChild)
        {
            setStatement((IStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
