/* This file was generated by SableCC (http://www.sablecc.org/). 
 * Then modified.
 */

package ast.node;

/**
 * The IExp subclass is used to group all nodes that are
 * expression nodes.
 * 
 * @author mstrout
 *
 */
public abstract class IExp extends Node
{
    public IExp(int _line_, int _pos_) {
        super(_line_,_pos_);
    }
}
